---
- hosts: production
  vars:
    project_path: /src/www/staging.dxlab.sl.nsw.gov.au
  tasks:
    - name: Set some variable
      set_fact:
        release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
        current_path: "{{ project_path }}/current"
    - name: Retrieve current release folder
      command: readlink -f current
      register: current_release_path
      ignore_errors: yes
      args:
        chdir: "{{ project_path }}"
    - name: Create new folder
      file:
        dest={{ release_path }}
        mode=0755
        recurse=yes
        state=directory
    - name: Clone the repository
      git:
        repo: git@github.com:slnsw/dxlab-website.git
        dest: "{{ release_path }}"
    - name: Update npm
      npm:
        path={{ release_path }}
    - name: Update symlink
      file:
        src={{ release_path }}
        dest={{ current_path }}
        state=link
    - name: Delete old pm2 process
      command: pm2 delete ws-node
      ignore_errors: yes
    - name: Start pm2
      command: pm2 start {{ current_path }}/server.js --name dxlab-website
